spring:
  application:
    name: gestao-produtos

  datasource:
    url: jdbc:postgresql://localhost:5432/gestao_produtos
    username: ${DB_USERNAME}
    password: ${DB_PASSWORD}

  jpa:
    hibernate:
      ddl-auto: validate
    show-sql: true
    properties:
      hibernate:
        format_sql: true
